format_version: 10
pipelines:
  expense-tf-destroy:
    group: terraform
    materials:
      git-683112d:
        git: https://github.com/a78devops/expense-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:wQGBZGdlHbYPyO5YwMH4ZQ==:ZcyP6UULRTBgjrVot93qp1ShNBdSQms+v0Vs/5excJg=
    stages:
      - dev:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: {command: terraform, arguments: [ "init", "-backend-config=env-dev/state.tfvars" ], run_if: passed}
                - exec: {command: terraform, arguments: [ "destroy", "-var-file=env-dev/main.tfvars", "-auto-approve" ], run_if: passed}

